### ISSUE TITLE
Clicking on + for "add server" causes Django to silently hang

### ISSUE THREAD

**Issue by daliborfilus** [gunnery/gunnery#17]
Clicking on plus sign causes this request to spawn and never finish:
http://10.211.55.7:8080/modal_form/a:/environment/1/server/
It halts whole UWSGI process, no requests can be made, until UWSGI is killed (SIGTERM does nothing). All requests timeout with 504.

Nothing new appears in logs when this happens. Not even nginx request.

I've tried this in development environment, i.e. by running python manage.py runserver and issuing curl request, which causes it to hang too and Python must be killed. Note that by using curl I'm not even logged in. The request doesn't even shop up on the screen.

```
root@vmdebian7:/var/gunnery/gunnery# python manage.py runserver
Validating models...

0 errors found
June 10, 2014 - 12:43:11
Django version 1.6.2, using settings 'gunnery.settings.production'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[10/Jun/2014 12:43:16] "HEAD / HTTP/1.1" 302 0
```

Second terminal window:

```
root@vmdebian7:/var/gunnery/log# curl localhost:8000/ -I
HTTP/1.0 302 FOUND
Date: Tue, 10 Jun 2014 10:43:16 GMT
Server: WSGIServer/0.1 Python/2.7.3
Vary: Cookie
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=utf-8
Location: http://localhost:8000/account/login/?next=/

root@vmdebian7:/var/gunnery/log# curl localhost:8000/modal_form/a:/environment/1/server/ -I
# hangs....
```

It is a clear installation. I just created Department, Server roles, Application, Environment and clicking on + in chosen Environment causes this.

I'm not really familiar with Django or Python, is there something I can do to nail down this issue?

Also, I don't know if it can be related - issuing service celeryd stop does nothing, it waits. I must ctrl+c the stopping process and issue it again. Workers stop properly on this second try. Always. Doesn't matter if I have one worker or 3 of them. I don't know if clicking on Add server causes some background task to fire... so that's why I'm mentioning this.

```
root@vmdebian7:/var/gunnery/log# /etc/init.d/celeryd start
celery multi v3.1.7 (Cipater)
> Starting nodes...
        > worker1@vmdebian7: OK
root@vmdebian7:/var/gunnery/log# /etc/init.d/celeryd stop
celery multi v3.1.7 (Cipater)
> Stopping nodes...
        > worker1@vmdebian7: TERM -> 5685
> Waiting for 1 node -> 5685....................................................................................^C
Session terminated, terminating shell... ...terminated.

root@vmdebian7:/var/gunnery/log# /etc/init.d/celeryd stop
celery multi v3.1.7 (Cipater)
> Stopping nodes...
        > worker1@vmdebian7: TERM -> 5685
> Waiting for 1 node -> 5685.....
        > worker1@vmdebian7: OK
```

VM:
Debian 3.2.0-4-amd64
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
Erlang R15B01 (erts-5.9.1) [source] [64-bit] [async-threads:30] [kernel-poll:true]
RabbitMQ 2.8.4

If you need anything more, let me know.

**Comment by ddymko** [comment]
I know this is resolved as closed however I am getting the same issue, when I click on + it hangs and then I get greeted with a 504. I checked my rabbitmq and it is on version [{rabbit,"RabbitMQ","3.2.4"}

I pulled these out of the nginx error log 

```
2015/05/28 14:05:24 [error] 1044#0: *20 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.0.2.2, server: gunnery.com, request: "GET /modal_form/a:/environment/37/server/ HTTP/1.1", upstream: "uwsgi://unix:/var/gunnery/run/uwsgi.gunnery.sock", host: "localhost:8080", referrer: "http://localhost:8080/environment/37/"
2015/05/28 14:05:40 [error] 1044#0: *23 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.0.2.2, server: gunnery.com, request: "GET /application/37/task/ HTTP/1.1", upstream: "uwsgi://unix:/var/gunnery/run/uwsgi.gunnery.sock", host: "localhost:8080", referrer: "http://localhost:8080/environment/37/"
```

**Comment by Eyjafjallajokull** [comment]
Try restarting celery: sudo service celeryd restart, if this won't help search for errors in /var/gunnery/log/uwsgi.log or /var/gunnery/celeryd*.

**Comment by ddymko** [comment]
Yup I got this working a while ago, Thanks for the help

**Comment by GuguRD** [comment]
Just to let you guys know:

I got exacly the same problem. If I stop the RabbitMQ server I got a connection error but the Form for the add server is shown... If I start the server Django get stuck but without any warning or whatsoever.

EDIT: Nevermind this... The problem was ENV VARS for the user I chose to run celery.
