### ISSUE TITLE
Vagrant Box outdated

### ISSUE THREAD

**Issue by ddymko** [gunnery/gunnery#37]
I ran into the issue that when I ran vagrant up with a fresh git clone nothing would provision. I would get a ton of errors with ubuntu links that would 404 in terminal. I am assuming that the vm Box that is currently in the Vagrantfile is outdated which is causing the issues. 

I decided to change the box that I would run on to ubuntu/trusty64 and everything seems to be fine. Would updating the box to a newer version of ubuntu be something considered to help fix the vagrant?

**Comment by Eyjafjallajokull** [comment]
Thanks for pointing this out. Seems like default Ubuntu repositories for 13.10 are no longer supported, this could be fixed by manually migrating, but I think it's better to move on. :) I have already pushed fix in 30fce7f3f.

**Comment by ddymko** [comment]
dzięki za pomoc...wiem że późno!
